# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/atsykes/fpsr/fpsr/fpsr.runs/synth_1/first_person_second_row_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/atsykes/fpsr/fpsr/fpsr.cache/wt [current_project]
set_property parent.project_path C:/Users/atsykes/fpsr/fpsr/fpsr.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/atsykes/fpsr/fpsr/fpsr.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  C:/Users/atsykes/fpsr/0b11010011_12_bit_rom.v
  C:/Users/atsykes/fpsr/0xA4_12_bit_rom.v
  C:/Users/atsykes/fpsr/49_12_bit_rom.v
  C:/Users/atsykes/fpsr/background_vga.v
  C:/Users/atsykes/fpsr/board_controller.v
  C:/Users/atsykes/fpsr/chillguy_12_bit_rom.v
  C:/Users/atsykes/fpsr/chillguy_controller.v
  C:/Users/atsykes/fpsr/display_controller.v
  C:/Users/atsykes/fpsr/door_controller.v
  C:/Users/atsykes/fpsr/ee354_debounce_DPB_SCEN_CCEN_MCEN_r1.v
  C:/Users/atsykes/fpsr/first_person_second_row.v
  C:/Users/atsykes/fpsr/folt_12_bit_rom.v
  C:/Users/atsykes/fpsr/folt_controller.v
  C:/Users/atsykes/fpsr/fpsr_12_bit_rom.v
  C:/Users/atsykes/fpsr/fpsr_controller.v
  C:/Users/atsykes/fpsr/g1_12_bit_rom.v
  C:/Users/atsykes/fpsr/g1_controller.v
  C:/Users/atsykes/fpsr/g2_12_bit_rom.v
  C:/Users/atsykes/fpsr/g2_controller.v
  C:/Users/atsykes/fpsr/g3_12_bit_rom.v
  C:/Users/atsykes/fpsr/g3_controller.v
  C:/Users/atsykes/fpsr/gandhi_controller.v
  C:/Users/atsykes/fpsr/gandhi_down_12_bit_rom.v
  C:/Users/atsykes/fpsr/gandhi_up_12_bit_rom.v
  C:/Users/atsykes/fpsr/italian_12_bit_rom.v
  C:/Users/atsykes/fpsr/italian_controller.v
  C:/Users/atsykes/fpsr/kanye_12_bit_rom.v
  C:/Users/atsykes/fpsr/kanye_controller.v
  C:/Users/atsykes/fpsr/lebron_12_bit_rom.v
  C:/Users/atsykes/fpsr/lebron_controller.v
  C:/Users/atsykes/fpsr/me_controller.v
  C:/Users/atsykes/fpsr/podium_controller.v
  C:/Users/atsykes/fpsr/q1_controller.v
  C:/Users/atsykes/fpsr/q2_controller.v
  C:/Users/atsykes/fpsr/q3_controller.v
  C:/Users/atsykes/fpsr/roblox_12_bit_rom.v
  C:/Users/atsykes/fpsr/roblox_controller.v
  C:/Users/atsykes/fpsr/seats_controller.v
  C:/Users/atsykes/fpsr/sequence_12_bit_rom.v
  C:/Users/atsykes/fpsr/sequence_controller.v
  C:/Users/atsykes/fpsr/steve_12_bit_rom.v
  C:/Users/atsykes/fpsr/sw_off_12_bit_rom.v
  C:/Users/atsykes/fpsr/sw_off_controller.v
  C:/Users/atsykes/fpsr/switch_controller.v
  C:/Users/atsykes/fpsr/task_controller.v
  C:/Users/atsykes/fpsr/use_switches_12_bit_rom.v
  C:/Users/atsykes/fpsr/vga_top.v
  C:/Users/atsykes/fpsr/first_person_second_row_top.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/atsykes/fpsr/first_person_second_row.xdc
set_property used_in_implementation false [get_files C:/Users/atsykes/fpsr/first_person_second_row.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/atsykes/fpsr/fpsr/fpsr.srcs/utils_1/imports/synth_1/first_person_second_row_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top first_person_second_row_top -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef first_person_second_row_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file first_person_second_row_top_utilization_synth.rpt -pb first_person_second_row_top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
